### ISSUE TITLE
How to treat hardware connected via I²C

### ISSUE THREAD

**Issue by gandy92** [MrYsLab/Telemetrix4Esp32#5]
I've successfully installed a Telemetrix server on my DFRobot Romeo Mini ESP32-C3 board. It's a neat little board with few peripherals, which work fine with the example server you provided.

Now I'm thinking about adding some additional hardware like a PCA9685 to drive some more servos, or a GPIO expander for some more digital input and output lines. Also, I'd like to be able to trigger output of pre-recorded sounds or control a bunch of neopixel RGB LEDs. 

So my question is, how could this be approached? Obviously, the client software should not have to care about whether some hardware is attached directly to a pin of the SOC or to some intermediate hardware. 

So maybe a valid approach would be to introduce some "virtual" pin numbers in the firmware (e.g. virtual pins 100..115 map to channels 0..15 of the PCA9685, pins 120..135 map to the 16 IO pins of a GPIO expander).  All relevant handler functions would need to check if a virtual pin is accessed and in that case use the external hardware instead of a GPIO on the SOC. 

Another approach would introduce additional devices but to my understanding this would require extending the protocol which would also affect client software. Eventually I'd like to control my board with Scratch 3 and I'd like to introduce as few changes as absolutely necessary.

What is your take on this, how do you think this could best be approached?

**Comment by MrYsLab** [comment]
The PCA9685 is an i2c-type device. I wrote some code to control it using telemetrix a few years back. There is a[ version I wrote for ESP-8266](https://github.com/MrYsLab/telemetrix-extensions/blob/master/examples/pca9685/telemetrix_pca_nodemcu.py) that should be adaptable for the ESP32. 

NeoPixels require very critical timing. Some i2c drivers exist, but I believe they do not provide standalone timing. Modifying Telemetrix4ESP32 would not work either because there would be no way to guarantee the timing. If you are willing to switch to Raspberry Pi PicoW, I have a [NeoPixel driver](https://github.com/MrYsLab/NeoPixelConnect) for the Raspberry Pi Pico and PicoW. The Pico boards have additional processors called PIOs that handle all the timing while the rest of the code can run "normally." There is a [telemetrix library ](https://mryslab.github.io/telemetrix-rpi-pico-w/)for the Pico and PicoW. 

What does your design entail for triggering the output of pre-recorded sound? You will probably need something like the [DFPlayer Mini](https://www.dfrobot.com/product-1121.html), but I am unsure how one would select between various MP3 files. Sorry, but this is not something I am knowledgeable about.

**Comment by MrYsLab** [comment]
There is an i2c [neopixel driver board](https://www.adafruit.com/product/5766) that will handle the timing. However, you must convert the [Arduino library](https://github.com/adafruit/Adafruit_Seesaw) to a Telmetrix Python i2c script. If you look at the code in the link above for the PCS9685, that is precisely what I did for that device.

It is not a trivial task, but it could potentially work. The Adafruit code can be convoluted and difficult to follow because of all of its interdependencies.

**Comment by gandy92** [comment]
Thank you for pointing this out, I had read but forgot that Telemetrix can tunnel I²C, that's a great feature, indeed. Actually, I like the idea using a RP2040 for timing critical stuff. It should be possible to implement an I²C slave interface and expose a small set of higher-level commands. Definitely something to look into.

For testing, I will check out the ESP-8266 code you linked to. Down the line, I'll want to control this I²C attached hardware from Scratch 3 - I've read your blog on how to accomplish this, but do you happen to have some I²C-related example at hand I can study?

**Comment by MrYsLab** [comment]
I assume you want to use specific i2c devices from a Scratch extension and not have a generalized set of i2c programming blocks. 

I have not implemented any i2c devices for Scratch because I would not know which devices to choose. If, for example,  I choose a specific accelerometer, a user may wish to use a different device with different capabilities. 

That being said, that does not mean that Scratch can't support i2c for specific i2c devices.
To do so, you'll need to be familiar with the JavaScript-based Scratch extensions scheme. The Scratch extension specification documentation is incorrect in many places. I documented my journey in creating extensions [beginning with the blog article](https://mryslab.github.io/bots-in-pieces/scratch3/gpio/2019/09/15/scratch3-1.html). You would need to add new Scratch blocks to support the i2c devices. To do so, [this JavaScript file](https://github.com/MrYsLab/s3onegpio/blob/esp32/scratch-vm/src/extensions/scratch3_onegpioEsp32/index.js) would need to be modified. Just so you know, the comment at the top of the file is incorrect; this code is for the ESP-32. Building the Scratch code must be done on a Linux-based machine, using specific versions of node.js and yarn. Also, please note that the code is in the esp32 branch of the repository.

The Python side needs an understanding of [python-banyan](https://mryslab.github.io/python_banyan/#users_guide/) and the[ OneGPIO](https://mryslab.github.io/python_banyan/gpio_intro/) protocol.

You would need to modify the [ESP-32 gateway](https://github.com/MrYsLab/s3-extend/blob/master/s3_extend/gateways/esp32_gateway.py). I would place as much as possible of the i2c device initialization code here. In this way, the Scratch extension would only be concerned with a single command to do a read of the i2c device and not be concerned with the device's initialization.

If you have any questions, I would be happy to answer them.

**Comment by gandy92** [comment]
Now, that sounds like quite a rabbit hole to dive into. I understand why you haven't implemented any I2C device directly in scratch, and given the fact that the esp-32 gateway would need modification anyway, it's probably best to rather have all I2C related code in there and only expose higher level functions to scratch. In the end, an 8-year old should be able to use it, so I'd really prefer to hide as much implementation details as possible. I'll have to get a better understanding of how things work and interact to see if that is feasible, but with the starting points you provided I should be able to begin. Will get back on your offer to answer some questions, though.

**Comment by MrYsLab** [comment]
I am going to close this issue. If you have any questions or comments, you can still post here, and I will see the post. If necessary, I can always re-open the issue.
